In [9]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])

In [10]:
slice1=a[2:6]
print(slice1)

[3 4 5 6]


In [11]:
slice2=a[::2]
print(slice2)

[1 3 5 7 9]


In [12]:
rev=a[::-1]
print(rev)

[9 8 7 6 5 4 3 2 1]


In [16]:
b=np.array([[1,3,5,6],[2,4,5,7]])

In [18]:
subarray=b[0:2,1:3]
print(subarray)

[[3 5]
 [4 5]]


In [23]:
col1=b[:,0]
print(col1)

[1 2]


In [26]:
row1=b[0,:]
print(row1)

[1 3 5 6]


In [28]:
print(b[0,0])
print(b[1,2])

1
5


In [30]:
c=np.array([10,20,30,40,50,60])

50


In [31]:
print(c[1])

20


In [33]:
print(c[-2])

50


In [34]:
print(c[1:4])

[20 30 40]


In [36]:
print(c[c>25])

[30 40 50 60]


In [37]:
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])

In [38]:
hj=np.hstack((ar1,ar2))
print(hj)

[[1 2 5 6]
 [3 4 7 8]]


In [39]:
vj=np.vstack((ar1,ar2))
print(vj)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
dj=np.dstack((ar1,ar2))
print(dj)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [43]:
s1=np.split(a,3)
print(s1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [46]:
s2=np.array_split(a,4)
print(s2)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
