In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
#program 7.1
import numpy as np
c=np.zeros((5,3))
print("\n Array with all zeros\n",c)

#program 7.2
import numpy as rnp
r=rnp.random.random((5,3))
print("\n Array with random values/n",r)
print("\n No of dimensions:",arr.ndim)

#program7.3
import numpy as snp
s=snp.arange(0,105,5)
print("\n Strip size array \n",s)

#program7.4
arr=rnp.array([[1,2,3],[5,6,7],[9,10,11],[13,14,15],[17,18,19]])
newarr=arr.reshape(3,5)
print("\n Reshaped array\n",newarr)


 Array with all zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array with random values/n [[0.44791277 0.73017183 0.42810728]
 [0.06562999 0.2597781  0.68459939]
 [0.0828584  0.14950827 0.15020063]
 [0.31908719 0.53807832 0.96851586]
 [0.74857651 0.11209757 0.66541061]]

 No of dimensions: 2

 Strip size array 
 [  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]

 Reshaped array
 [[ 1  2  3  5  6]
 [ 7  9 10 11 13]
 [14 15 17 18 19]]


In [16]:
#program8
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
flat=arr.flatten()
print("Flattened array;\n",flat)

Flattened array;
 [1 2 3 4 5 6 7 8 9]


In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n No. of dimensions:",arr.ndim)


 No. of dimensions: 2


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n Array element type:\n",arr.dtype)


 Array element type:
 int32


In [6]:
newarr=arr.astype('f')
print("converted array:\n ",newarr)
print("converted array type:\n ",newarr.dtype)

converted array:
  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
converted array type:
  float32


In [8]:
print("size of the array:",arr.size)

size of the array: 9
